version: '3'

services:
  app:
    container_name: rcd-app
    build: ./rcd-app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/rcd
    restart: unless-stopped
    volumes:
      - ./rcd-app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rcd-network

  auth:
    container_name: rcd-auth
    build: ./rcd-auth-server
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/rcd
    restart: unless-stopped
    networks:
      - rcd-network

  web:
    container_name: rcd-web
    build: ./esports-rcd-frontend
    ports:
      - "8080:3000"
    depends_on:
      - app
      - auth
    restart: unless-stopped
    networks:
      - rcd-network

  mongo:
    container_name: rcd-mongo
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - rcd-network

volumes:
  mongodb_data:

networks:
  rcd-network:
    name: rcd-network